-- Baseline schema for a brand-new Durable Cloud Journey PostgreSQL database.
-- Later migrations remain safe to run after this file.

BEGIN;

CREATE TABLE IF NOT EXISTS journeys (
    id VARCHAR(32) PRIMARY KEY,
    apm_id VARCHAR(64) NOT NULL,
    status VARCHAR(40) NOT NULL,
    current_step VARCHAR(64) NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    requested_by VARCHAR(128) NOT NULL,
    requested_by_email VARCHAR(320) NOT NULL,
    owner_subject VARCHAR(256) NOT NULL,
    role VARCHAR(40) NOT NULL,
    context JSON NOT NULL DEFAULT '{}'::json,
    last_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_journeys_apm_id UNIQUE (apm_id)
);

CREATE INDEX IF NOT EXISTS ix_journeys_apm_id
    ON journeys (apm_id);
CREATE INDEX IF NOT EXISTS ix_journeys_status
    ON journeys (status);
CREATE INDEX IF NOT EXISTS ix_journeys_owner_subject
    ON journeys (owner_subject);

CREATE TABLE IF NOT EXISTS journey_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journey_id VARCHAR(32) NOT NULL
        REFERENCES journeys (id) ON DELETE CASCADE,
    event_type VARCHAR(40) NOT NULL,
    from_state VARCHAR(40),
    to_state VARCHAR(40),
    actor_type VARCHAR(20) NOT NULL,
    actor_id VARCHAR(128) NOT NULL,
    message TEXT,
    metadata JSON NOT NULL DEFAULT '{}'::json,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_journey_events_journey_created
    ON journey_events (journey_id, created_at);

CREATE TABLE IF NOT EXISTS journey_operations (
    id VARCHAR(40) PRIMARY KEY,
    journey_id VARCHAR(32) NOT NULL
        REFERENCES journeys (id) ON DELETE CASCADE,
    operation_type VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    result JSON,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_journey_operations_journey_id
    ON journey_operations (journey_id);

COMMIT;
